[[plugins]]
  package = "@quarto/netlify-plugin-quarto"

[build]
  command = "quarto render --execute"
  publish = "_site"

[build.environment]
  QUARTO_VERSION = "1.7.31"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true